// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXAH_FQwDlEGB8yfUHb8zwolQvX3QU54Q',
    appId: '1:947297770659:android:4bd390e261fddcdd84f316',
    messagingSenderId: '947297770659',
    projectId: 'eduplay-af289',
    storageBucket: 'eduplay-af289.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTyOwuet3pBcVScvZ9yOviznFXTwUhW-0',
    appId: '1:947297770659:ios:0637750092c8dc1b84f316',
    messagingSenderId: '947297770659',
    projectId: 'eduplay-af289',
    storageBucket: 'eduplay-af289.appspot.com',
    iosBundleId: 'com.example.tolu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNaeaA4IfoKjLM1HfHCl-4A7FUPbemN2k',
    appId: '1:947297770659:web:a78b43b505a6c67384f316',
    messagingSenderId: '947297770659',
    projectId: 'eduplay-af289',
    authDomain: 'eduplay-af289.firebaseapp.com',
    storageBucket: 'eduplay-af289.appspot.com',
    measurementId: 'G-1FEPDYKD5R',
  );
}
